name: Actualizar Fuente de Elenemigos

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todos los días a medianoche
  workflow_dispatch: # Permite ejecutar el script manualmente cuando quieras

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar Scraper
        run: python scraper.py

      - name: Guardar cambios en el JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add elenemigos.json
          git commit -m "Auto-update: Fuente de Elenemigos actualizada" || exit 0
          git push
